# See LICENSE file for copyright and license details.

language: rust

cache: cargo

rust:
    - nightly
    - beta
    - stable

os:
    - linux
    - osx

sudo: false

addons:
    apt:
        packages:
            - libxxf86vm-dev
            - libxcursor-dev

script:
    - make && make test

# vim: set tabstop=4 shiftwidth=4 softtabstop=4 expandtab:
