language: rust

cache: cargo

rust:
    - nightly
    - beta
    - stable

matrix:
    allow_failures:
        - rust: nightly

os:
    - linux
    - osx

sudo: false

script:
    - make && make test
