# See LICENSE file for copyright and license details.

language: rust

rust:
    - nightly
    - beta
    - stable

sudo: false

addons:
    apt:
        packages:
            - libxxf86vm-dev
            - libxcursor-dev

script:
    - make && make test

# vim: set tabstop=4 shiftwidth=4 softtabstop=4 expandtab:
