[package]

name = "marauder"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "marauder"
crate-type = ["staticlib", "rlib"]

[dependencies.glutin]
features = ["window"]
git = "https://github.com/tomaka/glutin"

[dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"
 
[dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
