[package]

name = "zoc"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[[bin]]
name = "zoc"

[target.arm-linux-androideabi.dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"

[dependencies.visualizer]
path = "./src/visualizer/"
