[package]

name = "visualizer"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "visualizer"

[dependencies.glutin]
version = "*"
features = ["window"]

[dependencies.core]
path = "../core/"

[dependencies.common]
path = "../common/"

[dependencies.zgl]
path = "../zgl/"

[dependencies]
cgmath = "*"
time = "*"
rand = "*"
