[package]

name = "zoc_gl"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]
build = "build.rs"

[lib]
name = "zoc_gl"

[build-dependencies.khronos_api]
git = "https://github.com/bjz/gl-rs"

[build-dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs"

