[package]

name = "zoc_gl"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]
build = "build.rs"

[lib]
name = "zoc_gl"

[build-dependencies]
khronos_api = "*"
gl_generator = "*"

[dependencies]
libc = "*"
gl_common = "*"
