[package]

name = "core"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "core"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.common]
path = "../common"

[dependencies]
rand = "*"
