[package]

name = "core"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "core"
doctest = false

[dependencies.common]
path = "../common"

[dependencies]
cgmath = "*"
rand = "*"
num = "*"
