[package]

name = "common"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "common"

[target.arm-linux-androideabi.dependencies.android_glue]
git = "https://github.com/tomaka/android-rs-glue"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
