[package]

name = "common"
version = "0.0.1"
authors = ["ozkriff <ozkriffgmail.com>"]

[lib]
name = "common"

[target.arm-linux-androideabi.dependencies]
android_glue = "0.1.3"

[dependencies]
cgmath = "*"
